# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink: /:title/
relative_permalinks: true

# Setup
title:               Gerald
tagline:             'counselling and elearning resources online wellington'
description:         'MBA, MEd, MCouns'
url:                 http://gerald.nz
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Gerald Lee Jordan
  url:               https://twitter.com/geraldleejordan
  email:             jerryleejordan@gmail.com

# Custom vars
version:             1.0.0

#Added by Jerry
timezone: Pacific/Auckland
